name: lost_and_found_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
